apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    exercice: exercice2.1
    app: web
  name: exo2.1
spec:
  replicas: 4
  selector:
    matchLabels:
      exercice: exercice1.1
      app: web
  template:
    metadata:
      labels:
        exercice: exercice1.1
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
      - image: tauffredou/quote-logger
        imagePullPolicy: IfNotPresent
        name: quote-logger
