apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: exo5-staging
spec:
  rules:
  - host: staging.exo5.minikube.local
    http:
      paths:
      - backend:
          serviceName: exo5-staging
          servicePort: 80
