apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    exercice: exercice5
    app: web
    track: stable
  name: exo5-stable
spec:
  replicas: 4
  selector:
    matchLabels:
      exercice: exercice5
      app: web
      track: stable
  template:
    metadata:
      labels:
        exercice: exercice5
        app: web
        track: stable
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
      - image: tauffredou/quote-logger
        imagePullPolicy: IfNotPresent
        name: quote-logger
